upstream add_backend {
    server master:7070;
}

upstream get_backend{
    server replica1:7070;
    server replica2:7070;
    server master:7070 backup;
}

server {
    listen 80;
    server_name localhost;
    http2 on;
    location = /api/v1/addValue {
        limit_except POST {
            return 405;
        }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type $content_type;
        proxy_read_timeout 60s;
        proxy_pass http://add_backend;
    }
    location = /api/v1/value/[^/]+$ {
        limit_except GET {
            return 405;
        }
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Content-Type $content_type;
        proxy_read_timeout 60s;
        proxy_pass http://get_backend;
    }
}